### ISSUE TITLE
Importing from npm doesnt work

### ISSUE THREAD

**Issue by IceSentry** [RobotWebTools/ros2djs#36]
In my project I use vue and npm to build my UI. When I install this lib from npm I can't import it in my project. If I import it, it simply doesn't find the lib for some reason. I noticed that the dependencies aren't specified in package,json so I installed them manually. Unfortunately it still doesn't work.

**Comment by bradnez** [comment]
Having the same issue.

**Comment by unsalted** [comment]
I would love to use this lib, but it is so far away from modern practices, that it's too much hassle to get up and running.  Dependencies should NEVER be globally required.  I may take a crack at it if I decide this lib is a necessity, but... it may be tough.

**Comment by ferdinandyb** [comment]
We have the exact same issue trying to get this working with vue. Has anybody come up with a solution? Roslib works fine, but ros2d is not found :(

**Comment by kPatch** [comment]
@priestoferis @unsalted  I made some modifications, and got it working with ReactJS in the browser and Electron. In short, the "npm module" is not a JavaScript module, just a plain script - other dependencies are also broken. I will make a pull request some time next week after my school semester is over.

**Comment by ferdinandyb** [comment]
@kPatch that would be super helpful!

**Comment by asvinp** [comment]
@kPatch was wondering how you were able to get it working with ReactJS?

**Comment by Northo** [comment]
This would be super helpful!

**Comment by colmex** [comment]
Any update on this?

**Comment by ferdinandyb** [comment]
@kPatch Have you maybe had time to do that patch?

**Comment by rohanshukla94** [comment]
This is strange in the bower.json file it says 
"description": "(BOWER IS DEPRECATING! Please use npm version of ros2d). 2D Visualization Library for use with the ROS JavaScript Libraries",

But we can't use the npm version of the ros2d.. -_-

**Comment by AnasMK** [comment]
@kPatch could you please share how did you fix this, thanks

**Comment by Ninja-nick-s** [comment]
Hey everyone I was working with ros2d using react I encountered the same issue But I resolved it by just adding 
`module.exports = ROS2D;`
at the end of  ros2d.js inside build folder of ros2d in node_modules.
And then simply used all functions present into it by importing that file using
`import ROS2D from "node_modules/ros2d/build/ros2d";`
now I am able to use functions by just calling lets say ROS2D.viewer or any other function.
Its all because ros2d.js is just simply plain script with different functions. But you can work with it.
I hope this helps.

**Comment by MatthijsBurgh** [comment]
I have just released a new version. Please check if there are any issues.

Otherwise we could try the suggestion of @Ninja-nick-s.

I don't have a test example. So if somebody has one, please share.

**Comment by MatthijsBurgh** [comment]
What do you think of https://github.com/RobotWebTools/ros2djs/pull/92?

**Comment by snorresovold** [comment]
> I have just released a new version. Please check if there are any issues.
> 
> Otherwise we could try the suggestion of @Ninja-nick-s.
> 
> I don't have a test example. So if somebody has one, please share.

Hey, I have some issues with importing to a react project with npm, same as described before.
I have also tried @Ninja-nick-s  idea but that doesn't seem to work either, how do I fix this?

**Comment by MatthijsBurgh** [comment]
Which version are you using?
