### ISSUE TITLE
Map Not Scaling

### ISSUE THREAD

**Issue by ghost** [RobotWebTools/ros2djs#37]
Hello,

I am having trouble with visualizing the map. The problem is that most of the space occupied by the canvas in the browser is unknown space. I have tried to play with **scaleToDimensions** function but it is not helping at all. 

+  Map is not updating in real time. A bigger map can be seen in rviz but the browser dont seems to update.

Below is an example image. More bigger maps produce more bad preview.

![screenshot from 2018-09-10 15-19-19](https://user-images.githubusercontent.com/40040000/45297317-ae672e00-b50d-11e8-988f-ce802a97328d.png)

**Comment by YugAjmera** [comment]
Can you send your code ?

**Comment by MatthijsBurgh** [comment]
It scales everything to be in view. Even unknown space. In case you don't want that, make sure the published map is smaller.
