### ISSUE TITLE
build failed ros2djs by can not load library.

### ISSUE THREAD

**Issue by drgnman** [RobotWebTools/ros2djs#44]
My Program Environment is Node.js + Vue.js.
I installed ros2d by `npm install ros2d`

Build Problem:

> ERROR Failed to compile with 1 errors
This dependency was not found:
`* ros2d in ./node_modules/cache-loader/dist/cjs.js??ref--12-0~./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js??ref--18-0~./node_modules/cache-loader/dist/djs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
To install it, you can run: npm install --save ros2d

So, I play `npm install ros2d` again, but can't resolve this problem.
Please help me.

Environment:
Ubuntu: 16.04
nodejs:  v12.16.2
npm:      v6.14.4
vue/cli:   v4.3.1
ros2d:    v0.9.0

**Comment by jaguardo** [comment]
I attempted similar.
```
yarn add ros2d
```
and in the project
```
import ROS2D from 'ros2d'
```

did not solve the issue
```
Module not found: Can't resolve 'ros2d' in
```

**Comment by ehvenimunis** [comment]
I have similar problem

**Comment by lagartoxa** [comment]
Similar problem here but with React. I run **yarn add ros2d** without any problems but when I run **yarn build**, I get the message:

Cannot find module: 'ros2d'. Make sure this package is installed.
You can install this package by running: yarn add ros2d.

**Comment by rohanshukla9** [comment]
Stupid packages aren't working  then why is it on npm in first place? Do they even test require their own package to see if it's working?

Same issue!

**Comment by AnasMK** [comment]
does anyone find a way to solve this!

**Comment by f-y-l** [comment]
WHO CAN HELP ME !!!
My Program Environment is Node.js + Vue.js.
I installed ros2d by npm install ros2d

Build Problem:

ERROR Failed to compile with 1 errors
This dependency was not found:
`* ros2d in ./node_modules/cache-loader/dist/cjs.js??ref--12-0~./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js??ref--18-0~./node_modules/cache-loader/dist/djs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/dashboard/Dashboard.vue?vue&type=script&lang=js&
To install it, you can run: npm install --save ros2d

**Comment by f-y-l** [comment]
> WHO CAN HELP ME !!! My Program Environment is Node.js + Vue.js. I installed ros2d by npm install ros2d
> 
> Build Problem:
> 
> ERROR Failed to compile with 1 errors This dependency was not found: `* ros2d in ./node_modules/cache-loader/dist/cjs.js??ref--12-0~./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js??ref--18-0~./node_modules/cache-loader/dist/djs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/dashboard/Dashboard.vue?vue&type=script&lang=js& To install it, you can run: npm install --save ros2d

I kown how to kill this problem!

**Comment by rohanshukla94** [comment]
You can't because this library is UMD library and doesn't ship a CommonJS or es6 module interface. If you still want to use you can use createjs with webpack and ship your own version to npm

**Comment by MatthijsBurgh** [comment]
You all are free to help convert this to ESM or compile it such that we provide multiple version

**Comment by MatthijsBurgh** [comment]
What do you think of https://github.com/RobotWebTools/ros2djs/pull/92?
