### ISSUE TITLE
touch events in viewer

### ISSUE THREAD

**Issue by halejo-as** [RobotWebTools/ros2djs#46]
Hello, 

I am using a viewer to get a map in my page web I add also the pan and zoom tools following this example (https://github.com/RobotWebTools/ros2djs/pull/20/files) it works well in the desktop version with the mouse events.

But i cannot figure it out how to use the **_touch events_** , i tried with _ontouchstart_ and _touchstart_ and neither works
```

    viewer.scene.addEventListener('ontouchstart', function (event) {
        event.preventDefault();
        panView.startPan(event.touches[0].clientX, eevent.touches[0].clientY);
        mouseDown = true;
        console.log("touch");
    });
```

Thank you for your help

**Comment by funnyrabbitvu** [comment]
Hi @halejo-as ,
How do you use the pan and zoom to interact with the map?
Please give me some help! 
Thank you alot, sir.

**Comment by wen-da-ng** [comment]
> Hello,
> 
> I am using a viewer to get a map in my page web I add also the pan and zoom tools following this example (https://github.com/RobotWebTools/ros2djs/pull/20/files) it works well in the desktop version with the mouse events.
> 
> But i cannot figure it out how to use the **_touch events_** , i tried with _ontouchstart_ and _touchstart_ and neither works
> 
> ```
> 
>     viewer.scene.addEventListener('ontouchstart', function (event) {
>         event.preventDefault();
>         panView.startPan(event.touches[0].clientX, eevent.touches[0].clientY);
>         mouseDown = true;
>         console.log("touch");
>     });
> ```
> 
> Thank you for your help

If you're using Nav2Djs, and easeljs
add below at line 124 works for me
```
 createjs.Touch.enable(stage);
```
