### ISSUE TITLE
build failed ros2djs by can not load library (react project)

### ISSUE THREAD

**Issue by ehvenimunis** [RobotWebTools/ros2djs#57]
**I followed these steps in your project:**

npm install

and in the project

import ROS2D from 'ros2d'

did not solve the issue

Module not found: Can't resolve 'ros2d' in

**Comment by MatthijsBurgh** [comment]
Looks similar to #44

**Comment by rohanshukla94** [comment]
> Looks similar to #44

Looks similar but no solutions yet!

**Comment by AnasMK** [comment]
> Looks similar to #44

does anyone find a way to solve this

**Comment by MatthijsBurgh** [comment]
What do you think of https://github.com/RobotWebTools/ros2djs/pull/92?
