### ISSUE TITLE
Yarn add ros2d doesn't add the module

### ISSUE THREAD

**Issue by lagartoxa** [RobotWebTools/ros2djs#64]
Hi everyone,

I'm developing a project using React. I added the ros2d to my project by running:
`$ yarn add ros2d`

The output shows that the dependency was added:

yarn add v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @testing-library/user-event@12.7.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "admin-lte > bootstrap-switch@3.3.4" has incorrect peer dependency "bootstrap@^3.1.1".
warning "admin-lte > tempusdominus-bootstrap-4@5.39.0" has unmet peer dependency "moment-timezone@^0.5.31".
warning "admin-lte > tempusdominus-bootstrap-4@5.39.0" has unmet peer dependency "tempusdominus-core@5.19.0".
warning " > chartjs-plugin-colorschemes@0.4.0" has unmet peer dependency "chart.js@>= 2.5.0 < 3".
warning " > react-chartjs-2@2.11.1" has unmet peer dependency "chart.js@^2.3".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.20.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > sass-loader@11.0.1" has unmet peer dependency "webpack@^5.0.0".
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ ros2d@0.9.0
info All dependencies
└─ ros2d@0.9.0
Done in 4.71s.

When I run **yarn build**, I get this error:

yarn run v1.22.11
$ craco build
craco:  *** Cannot find ESLint loader (eslint-loader). ***
Creating an optimized production build...
Failed to compile.

./src/pages/current_amr_map/CurrentAmrMap.js
Cannot find module: 'ros2d'. Make sure this package is installed.

You can install this package by running: yarn add ros2d.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I could install and use roslib without any problems with **yarn add**. Also I tried to install the eventemitter2 and easeljs and ran **yarn build** again, but I'm still getting the same error

Could someone help me?

**Comment by MatthijsBurgh** [comment]
Does 'npm' do the trick? If that is the case I don't see the problem being in this library

**Comment by lagartoxa** [comment]
npm install ros2d give me some dependencies warnings:

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN sass-loader@11.0.1 requires a peer of webpack@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap-switch@3.3.4 requires a peer of bootstrap@^3.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN tempusdominus-bootstrap-4@5.39.0 requires a peer of tempusdominus-core@5.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ ros2d@0.9.0
added 356 packages from 137 contributors, removed 203 packages, updated 1787 packages and audited 2166 packages in 115.827s

152 packages are looking for funding
  run `npm fund` for details
  
  
  I tried to install those dependencies manually, but each dependency had more and more dependencies and I didn't go to the end of this loop

**Comment by MatthijsBurgh** [comment]
I have released a new version. Could you please check if the issue is fixed?

**Comment by MatthijsBurgh** [comment]
What do you think of https://github.com/RobotWebTools/ros2djs/pull/92?

**Comment by MatthijsBurgh** [comment]
Stale
